name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install nerdctl
        run: |
          wget -O nerdctl-1.7.2-linux-amd64.tar.gz https://github.com/containerd/nerdctl/releases/download/v1.7.2/nerdctl-full-1.7.2-linux-amd64.tar.gz
          tar Cxzvvf /usr/ nerdctl-1.7.2-linux-amd64.tar.gz

      - name: Build Docker image with nerdctl
        run: |
          nerdctl build -f path/to/Dockerfile -t your-image-name:tag .

