name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Kaniko builder
      uses: aevea/action-kaniko@v0.10.0
      with:
        registry: registry.skver.space
        username: skver
        password: $DOCKER_LOGIN_PW
        image: skverspace
        tag: latest
