name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2.12
      with:
        image: skverspace
        tags: latest
        containerfiles: |
          ./Dockerfile



