name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.skver.space
        username: skver
        password: ${{ secrets.DOCKER_LOGIN_PW }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: registry.skver.space/skverspace:latest
    - name: pain
      run: |
           ssh root@192.168.0.104 << 'EOF'
            k3s kubectl -n ix-skver-space scale --replicas 0 deploy skver-space-ix-chart || true
            k3s kubectl -n ix-skver-space scale --replicas 1 deploy skver-space-ix-chart  || true
           EOF
